apiVersion: v1
kind: DeploymentConfig
metadata:
  annotations:
    kompose.cmd: kompose convert --provider=openshift
    kompose.version: 1.16.0 ()
  creationTimestamp: null
  labels:
    io.kompose.service: angular-starter
  name: angular-starter
spec:
  replicas: 1
  selector:
    io.kompose.service: angular-starter
  strategy:
    resources: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        io.kompose.service: angular-starter
    spec:
      containers:
      - args:
        - npm
        - run
        - start
        env:
        - name: HOST
          value: 0.0.0.0
        image: ' '
        name: angular-starter
        ports:
        - containerPort: 3000
        resources: {}
      restartPolicy: Always
  test: false
  triggers:
  - type: ConfigChange
  - imageChangeParams:
      automatic: true
      containerNames:
      - angular-starter
      from:
        kind: ImageStreamTag
        name: angular-starter:latest
    type: ImageChange
status: {}
