apiVersion: v1
kind: ImageStream
metadata:
  creationTimestamp: null
  labels:
    io.kompose.service: angular-starter
  name: angular-starter
spec:
  tags:
  - annotations: null
    from:
      kind: DockerImage
      name: angular-starter
    generation: null
    importPolicy: {}
    name: latest
status:
  dockerImageRepository: ""
