apiVersion: v1
kind: ImageStream
metadata:
  creationTimestamp: null
  labels:
    io.kompose.service: angular
  name: angular
spec:
  tags:
  - annotations: null
    from:
      kind: DockerImage
      name: tekleayele/excella-dashboard-ui:latest
    generation: null
    importPolicy: {}
    name: latest
status:
  dockerImageRepository: ""
