apiVersion: v1
kind: Service
metadata:
  annotations:
    kompose.cmd: kompose convert --provider=openshift
    kompose.version: 1.16.0 ()
  creationTimestamp: null
  labels:
    io.kompose.service: angular
  name: angular
spec:
  ports:
  - name: "4200"
    port: 4200
    targetPort: 8080
  selector:
    io.kompose.service: angular
status:
  loadBalancer: {}
