apiVersion: v1
kind: Service
metadata:
  annotations:
    kompose.cmd: kompose convert --provider=openshift
    kompose.version: 1.16.0 ()
  creationTimestamp: null
  labels:
    io.kompose.service: app
  name: app
spec:
  ports:
  - name: "4200"
    port: 4200
    targetPort: 4200
  - name: "49153"
    port: 49153
    targetPort: 49153
  selector:
    io.kompose.service: app
status:
  loadBalancer: {}
