apiVersion: v1
kind: ImageStream
metadata:
  creationTimestamp: null
  labels:
    io.kompose.service: app
  name: app
spec:
  tags:
  - annotations: null
    from:
      kind: DockerImage
      name: app
    generation: null
    importPolicy: {}
    name: latest
status:
  dockerImageRepository: ""
