version: '3'
services:
  excella-dashboard-ui:
    build: 
      dockerfile: Dockerfile
    command: "npm start"
    image: tekleayele/excella-dashboard-ui:latest
    ports:
      - "4200:4200"
      - "49153:49153"
    expose:
      - "4200"
      - "49153"